fixed a bug that broke my CIDER CLJS REPL, due to nil namespace
- I was getting errors like this:
;; ClojureScript REPL type: shadow
;; ClojureScript REPL init form: (do (require '[shadow.cljs.devtools.api :as shadow]) (shadow/watch :dev) (shadow/nrepl-select :dev))
;;
ERROR: Unhandled REPL handler exception processing message {:op eval, :ns [], :code (do (require '[shadow.cljs.devtools.api :as shadow]) (shadow/watch :dev) (shadow/nrepl-select :dev)), :session 7400cb51-94b7-4fb5-8f31-90294cd45083, :id 9}
java.lang.IllegalArgumentException: no conversion to symbol
	at clojure.core$symbol.invokeStatic(core.clj:598)
	at clojure.core$symbol.invoke(core.clj:591)
	at cider.nrepl.middleware.debug$maybe_debug.invokeStatic(debug.clj:684)
	at cider.nrepl.middleware.debug$maybe_debug.invoke(debug.clj:676)
	at cider.nrepl.middleware.debug$handle_debug.invokeStatic(debug.clj:725)
	at cider.nrepl.middleware.debug$handle_debug.invoke(debug.clj:720)
...

- cider-current-ns was returning nil namespace due to a missing case
in my advice-fn, causing clojure.core/symbol to fail